### ISSUE TITLE
Explore offline possibility for spotify

### ISSUE THREAD

**Issue by ericdall** [beatlink-epfl/beatlink#198]
When turning offline, the app should not do api calls anymore, nor try to catch the token.
When turning online again, the token should update if expired and respective api calls should be called.

**Comment by arthur-wolf** [comment]
After some research, here is the conclusion I have come to:
- When offline, the app will not be able to send api calls due to the lack of connection, and same can be said for requesting / refreshing the Spotify access token. This will later be implemented just like the offline mode for the other features (we will get the connection state in a top level composable - probably BeatLinkApp -  and pass it down to whatever composable needs it). That way, we can have two app modes (online / offline) and have different behaviours for each mode).
- When turning back online, API calls will implicitly be available again, and the token will refresh automatically as is the case now. If there is no token, the user will still be able to link their Spotify account just like they can for now.
